module.exports = {
  STATIC_ROUTES: [
    "/",

    "/blog",
    "/careers",
    "/services",

    "/privacy-policy",
    "/cookie-policy",
    "/affiliate-disclosure",
    "/disclaimer",
    "/terms-and-conditions",

    "/services/seo-services",
    "/services/web-design",
    "/services/ui-ux-design",
    "/services/social-media-marketing",

    "/claude-ai",
    "/free-website-templates",

    "/case-studies",
    "/case-studies/online-wine-shopping",

    "/seo-internship-pune",
    "/seo-internship-mumbai",
    "/remote-seo-internship",

    "/best-ai-tools-for-marketers",
    "/best-chatgpt-tools-for-marketers",

    "/resources/career",
    "/resources/career/free-ats-resume-checklist",
    "/resources/career/best-resume-builders",
    "/resources/career/best-ai-resume-builders",
    "/resources/career/best-ats-resume-tools",
    "/resources/career/best-resume-writing-services",
    "/resources/career/rezi-review",
    "/resources/career/resume-io-review",
    "/resources/career/zety-review",
    "/resources/career/rezi-vs-resume-io",
    "/resources/career/rezi-vs-zety",
    "/resources/career/resume-io-vs-zety",
    "/resources/career/topresume-review",
    "/resources/career/best-cover-letter-tools",
    "/resources/career/best-interview-preparation-tools",
    "/resources/career/best-online-courses-for-job-seekers",
    "/resources/career/best-english-speaking-courses",
    "/resources/career/best-writing-tools-for-job-seekers",
    "/resources/career/best-tools-for-freelancers",
    "/resources/career/best-career-development-platforms",
    "/resources/career/best-career-courses",
    "/resources/career/best-job-search-tools",
    "/resources/ui-ux-interview-questions",
    "/resources/figma-website-wireframe-kit",
    "/resources/ui-ux-designer-resume-template",
    "/resources/ux-case-study-template",
    "/resources/ui-ux-portfolio-checklist",
    "/resources/figma-shortcuts-cheat-sheet",
    "/resources/ui-design-checklist",
    "/resources/ux-research-starter-kit",
    "/resources/website-usability-checklist",
    "/resources/typography-cheat-sheet-ui-designers",
    "/resources/color-contrast-guide-ui-designers",
    "/resources/ui-ux-design-process-cheat-sheet",
    "/resources/seo-interview-questions",
    "/resources/digital-marketing-interview-questions",
    "/resources/react-interview-questions",
    "/resources/spoken-english-practice-sheet",
    "/resources/ui-ux-internship-starter-kit",
    "/resources/figma-auto-layout-cheat-sheet",
    "/resources/free-ui-ux-design-ebook",
    "/ui-ux-internship",
  ],
};